[package]
name = "Tap"
version = "2.1.0"
authors = []

[addresses]
tap = "_"

[dev-addresses]
tap = "0x3333"
integer_mate = "0xc4fb1d925938d1499dfd1ae4e041d0377a9a761f6da0a3c18f12a8aad7810e6d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-token"

[dependencies.IntegerMate]
git = "https://github.com/phatln/integer-mate.git"
rev = "bd450fbf2db88114f84ab90a67bd885c430882bb"
subdir = "aptos"

[dev-dependencies]
